name: Test URLs

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install html2text
      run: sudo apt-get install -y html2text
    - name: Test URLs
      run: ./test.sh
